<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon />
    <AssemblyName>AudioExtractor</AssemblyName>
    <RootNamespace>AudioExtractor</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AudioExtractor.Core\AudioExtractor.Core.csproj" />
    <None Include="3rdparty\ffmpeg.exe" CopyToOutputDirectory="PreserveNewest" Condition="Exists('3rdparty\ffmpeg.exe')" />
  </ItemGroup>
</Project>
